### ISSUE TITLE
How to send the data to any cloud

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-Raspberry-Pi-64-bits#3]
Can you please let me know if its possible to send the attendance data from raspberry to any cloud database ?
My question is more specific towards relay from C++ code to Cloud.  Im new to cloud hence just need your guidance not much.

**Comment by Qengineering** [comment]
Dear @rsingh2083,

1) Use only C++ in machine learning or computer vision. It's 10-40 times faster than Python due to its low level and compiled instead of interpreted.
2) You can use Python if you like in case of connecting to the cloud. Now, Python has the advances of being high level (a few lines of code doing a lot of things). And the most time is consumed by the traffic on the net. So, not much to gain if you use C++ here. 
3) Write information for the cloud in a file by your C++ app.
4) Invoke your Python cloud program by a timer (like _cron_) or on an event base (by the statement _system()_)in your C++ program. 
5) There are many good tutorials on the net covering this subject in detail with examples now you're able to use Python

Success!
