### ISSUE TITLE
Saving the recognized person name

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Recognition-Raspberry-Pi-64-bits#9]
Hi Sir,

I wanted to save person name on console and just after line number 113 of you main.cpp, I inserted small code to print person name and then save person name. Its printing the person name but it not saving person name. Can you please help. Where shall I insert these 4 lines to save recognized person name  ?

_main.cpp_
```
.....  //LINE 108, main.cpp 
switch(obj.NameIndex){     
            case -1: Str="Stranger"; break;
            case -2: Str="too tiny"; break;
            case -3: Str="Fake !";   break;
            default: Str=NameFaces[obj.NameIndex];
        }    // LINE 113 main.cpp

//MY CODE : PRINT PERSON NAME        
cout << "NAME DETECTED AS = " << Str << std::endl;
//END PRINT NAME

//SAVE NAME
 std::string nam= Str.c_str();
 std::cout << "SAVED NAME IN NAME = ", nam;
//END SAVE NAME
......
```
As you can see in output, its printing the person name but not saving it in the string `name`
====OUTPUT====
```
NAME DETECTED AS  = PERSON1  
SAVED NAME IN NAME = 
```
===============

**Comment by Qengineering** [comment]
@rsingh2083 ,

How would you save the name? 
One file with all the recognized persons listed?
Or one file per person?
Or one file a day / week?

Initial you code wasn't bad. However, working with streams involves << overload operations.
That's why the line `std::cout << "SAVED NAME IN NAME = ", nam;` never works, due to the comma (suggesting an argument)

Apart from the administration of managing the files and their names, the basic operations are:
```
(at the top of the main.cpp)
#include <stdio.h>
#include <string.h>
#include <fstream>

//after line 133
    ofstream myfile;

    //TFileName is the name to which the face will be appended. It can be a new file, or an existing
    myfile.open(TFileName);      

    if(myfile.is_open()){
        myfile << "SAVED NAME IN NAME =  " << Str << endl;
        myfile.close();
    }
    else cout << "Error writing the file" << endl;

```
Of course, you can open the file at the start of the program, write your names and closes in the end.
However, don't forget to close it. Especially important in the case of a unexpected program termination.

**Comment by rsingh2083** [comment]
Ok Sir
